<!--JQuery-->
<script src="https://code.jquery.com/jquery-3.1.1.min.js"   integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="   crossorigin="anonymous"></script>

<script>document.getElementById("mobile-nav").style.opacity = "0";</script> <!--For some reason the opacity isn't 0 immediately.-->

<!--AOS: Animate on scroll js library from http://michalsnik.github.io/aos/ -->
<script src="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.js"></script>

<!--Initialize AOS-->
<script> 
	AOS.init({
	  duration: 1200,
	});
</script>

<script src="js/open-nav.js"></script>

<!--Smooth scroll-->
<script src="js/smoothscroll.js"></script>

